### ISSUE TITLE
Unknown SE 

### ISSUE THREAD

**Issue by cxc6820** [kaizadp/suli2021#3]
# RA Calculation ----

RA_cores = fticr_data_key %>%
  left_join(dplyr::select(fticr_meta, formula, class), by = "formula") %>%
  group_by(DOC_ID, depth, Site, treatment, class) %>%
  dplyr::summarise(abund = sum(presence)) %>%
  filter(!is.na(class)) %>%
  ungroup %>%
  group_by(Site, DOC_ID) %>%
  dplyr::mutate(total = sum(abund), relabund = round((abund/total)*100,2))

  # Calculating Mean RA ----

RA_trt = RA_cores %>%
  group_by(DOC_ID, depth, Site, treatment, class) %>%
  dplyr::summarize(relabund2 = mean(relabund), 
                   
                   se = sd(relabund/sqrt(n())),
                   
                   relative_abundance = paste(relabund2, "\u00b1", se))

**Comment by kaizadp** [comment]
https://github.com/kaizadp/suli2021/blob/ebc7258f9d448c59d454161f8c2d9cae19a7dab9/tes_drought/code/FTICR_tes_drought_code_RelativeAbund_only.R#L14

cannot calculate SE because of individual DOC_ID.
