### ISSUE TITLE
NMR - renaming samples

### ISSUE THREAD

**Issue by cxc6820** [kaizadp/suli2021#4]
Issue - cannot rename the name because it is not exist regardless of the same name is presented in the table. I have to do this, in order to merge the corekey table into a single table. 

## process the peaks
peaks_processed = 
  peaks_rawdat %>% 
  filter(ppm >=0 & ppm <= 10) %>% 
  filter(Intensity > 0) %>% 
  # remove solvent regions
  #filter(!(ppm>DMSO_start & ppm<DMSO_stop)) %>% 
  #filter(!(ppm>WATER_start & ppm<WATER_stop)) %>% 
  filter(!is.na(ppm)) %>% 
  # remove peaks with 0 intensity, and peaks flagged as weak 
  filter(!Flags=="Weak") %>% 
  mutate(source = str_remove(source, paste0(PEAKS_FILES, "/"))) %>% 
  mutate(source = str_remove(source, ".csv")) %>% 
  dplyr::select(-Obs)

  #Renaming processed peak ----

peaks_processed_renamed = rename(peaks_processed,
                                 "DOC-074" = "tes_drought/data/nmr_data/peaks/074",
                                 "DOC-079" = "tes_drought/data/nmr_data/peaks/079",
                                 "DOC-081" = "tes_drought/data/nmr_data/peaks/081",
                                 "DOC-178" = "tes_drought/data/nmr_data/peaks/178",
                                 "DOC-179" = "tes_drought/data/nmr_data/peaks/179",
                                 "DOC-180" = "tes_drought/data/nmr_data/peaks/180",
                                 "DOC-185" = "tes_drought/data/nmr_data/peaks/185",
                                 "DOC-186" = "tes_drought/data/nmr_data/peaks/186",
                                 "DOC-187" = "tes_drought/data/nmr_data/peaks/187",
                                 "DOC-181" = "tes_drought/data/nmr_data/peaks/181",
                                 "DOC-182" = "tes_drought/data/nmr_data/peaks/182",
                                 "DOC-183" = "tes_drought/data/nmr_data/peaks/183",
                                 "DOC-188" = "tes_drought/data/nmr_data/peaks/188",
                                 "DOC-189" = "tes_drought/data/nmr_data/peaks/189",
                                 "DOC-190" = "tes_drought/data/nmr_data/peaks/190")

**Comment by kaizadp** [comment]
please include the permalink here

**Comment by kaizadp** [comment]
also - save, commit, and push all your changes to GitHub, so I can take a look at your most updated code.

**Comment by kaizadp** [comment]
saving the permalink here.

https://github.com/kaizadp/suli2021/blob/83edfef6c1063c0aa7287208cfba9616a8d8ae9a/tes_drought/code/NMR_tes_drought_code.R#L131

**Comment by kaizadp** [comment]
The`peaks_processed` data frame is in long form, which means all the samples are already in a single column. Your plan of `rename()` would work only in wide form, where each sample is a different column. Like in the FT-ICR-MS data frame. 

The samples are in the format 074, 075, etc.
![image](https://user-images.githubusercontent.com/50244730/124329126-c0dc0780-db3f-11eb-9407-59f67c76eeed.png)

In the corekey, the DOC_ID is in the format DOC-001, DOC-074, DOC-075, etc.
![image](https://user-images.githubusercontent.com/50244730/124329358-24663500-db40-11eb-9fa0-30238eddd192.png)

So we need to create a new column in `peaks_processed`, called DOC_ID, which will combine "DOC-" with the sample number (from the `source` column).

We do this using `mutate(DOC_ID = paste0("DOC-", source))`

https://github.com/kaizadp/suli2021/blob/44d64371ad1e90c9a029a90b3533bf711bc64ebc/tes_drought/code/NMR_tes_drought_code.R#L132-L146


This should now fix the problem, and will allow you to merge with the corekey.
